version: '3.7'

services:
  server:
    container_name: ga_server-dev
    image: ${DOCKER_IMAGE}
    depends_on:
      - postgres_db
    ports:
      - ${SERVER_PORT_OUT}:${SERVER_PORT}
    volumes:
      - ${ASSETS_PATH_OUT}:${ASSETS_PATH}
    networks:
      - internal-dev
    env_file:
      - dev.env

  postgres_db:
    container_name: ga_db-dev
    image: postgres:16-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT_OUT}:${POSTGRES_PORT}
    volumes:
      - postgres_db-dev:/var/lib/postgresql/data
    networks:
      - internal-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  swagger_ui:
    container_name: swagger_ui-dev
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_PORT_OUT}:8080
    environment:
      - SWAGGER_JSON=/docs/swagger.yaml
    volumes:
      - ./docs/:/docs

volumes:
  postgres_db-dev:


networks:
  internal-dev:
    driver: bridge
