version: '3.7'

services:
  server:
    image: ${DOCKER_IMAGE}
    depends_on:
      - postgres_db
    ports:
      - ${SERVER_PORT_OUT}:${SERVER_PORT}
    volumes:
      - ${ASSETS_PATH_OUT}:${ASSETS_PATH}
    networks:
      - internal
    env_file:
      - dev.env

  postgres_db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT_OUT}:${POSTGRES_PORT}
    volumes:
      - postgres_db-dev:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_db-dev:


networks:
  internal:
    driver: bridge
