galaxy_info:
  author: Jagerente
  description: Configure server for Genshin Academy
  company: Genshin Academy

  license: MIT

  min_ansible_version: 2.1

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags: []