name: Build and Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20"

      - name: Build Server
        run: |
          go build -o server ./cmd/web/main.go

      - name: Build Synchronization
        run: |
          go build -o sync ./cmd/sync/main.go

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            server
            sync

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Deploy server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: server
          target: ${{ vars.OUTPUT_DIR_DEV }}

      - name: Deploy sync
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: sync
          target: ${{ vars.OUTPUT_DIR_DEV }}

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x ${{ vars.OUTPUT_DIR_DEV }}/server
            sudo systemctl restart ${{ vars.SERVICE_NAME_DEV }}
            chmod +x ${{ vars.OUTPUT_DIR_DEV }}/sync
