name: Build and Deploy Docker PROD

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_IMAGE_PROD }}

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            docker-compose.prod.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Deploy docker-compose.prod.yaml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose.prod.yaml
          target: ${{ vars.OUTPUT_DIR_PROD }}

      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.ENV_PROD }}" > ${{ vars.OUTPUT_DIR_PROD }}/prod.env

      - name: Pull and restart docker container using service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl restart ${{ vars.SERVICE_NAME_PROD }}