name: Build and Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build
        run: |
          go build -o server

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: server

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: server-artifact

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: server
          target: ${{ vars.OUTPUT_DIR_DEV }}

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x ${{ vars.OUTPUT_DIR_DEV }}/server
            sudo systemctl restart ${{ vars.SERVICE_NAME_DEV }}
