name: Test build on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go get ./... && go mod tidy

      - name: Test with the Go CLI
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - name: Test Build Server
        run: |
          go build -o server ./cmd/web/main.go

      - name: Test Build Sync
        run: |
          go build -o sync ./cmd/sync/v2/main.go
