name: Test build on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Go
          uses: actions/setup-go@v3.5.0
          with:
            go-version: "1.20"
  
        - name: Install dependencies
          run: go mod download
    
        - name: Run tests
          run: go test ./...
            
        - name: Test Build Server
          run: |
            go build -o server ./cmd/web/main.go

        - name: Test Build Sync
          run: |
            go build -o sync ./cmd/sync/v2/main.go
